version: '3'
services:
  app:
    container_name: tp-flask-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - api

  api:
    container_name: tp-api
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: tp-db
    restart: always
    ports:
      - '3309:3306'
    environment:
      MYSQL_DATABASE: tp_database
      MYSQL_ROOT_PASSWORD: scrumbeasts
      MYSQL_USER: usuario
      MYSQL_PASSWORD: scrumbeasts
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      
volumes:
  app-data: