services:
  mysqldb:
    image: mysql
    restart: always
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: scrumbeast
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: tp-intro
    command: flask run --debug --host=0.0.0.0 --port=5005
    ports:
      - 5005:5005
    volumes:
      - .:/code
    depends_on:
      - mysqldb
