services:
  flask-app:
    container_name: tp-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5000:5000"
    volumes:
      - .:/app

  api:
    container_name: tp-api
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - .:/app

volumes:
  app-data: