services:
  db:
    image: mysql:latest
    container_name: tp-intro-db
    restart: always
    ports:
      - '3309:3306'
    environment:
      MYSQL_DATABASE: tp_database
      MYSQL_ROOT_PASSWORD: scrumbeasts
      MYSQL_USER: usuario
      MYSQL_PASSWORD: scrumbeasts
    volumes:
      - ./database/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    container_name: tp-intro-app
    command: 
      - flask run --debug --host=0.0.0.0 --port=5000
      - python3 new_api.py --debug --host=0.0.0.0 --port=5001
    ports:
      - 5000:5000
      - 5001:5001
    volumes:
      - .:/code
    depends_on:
      - db
