#-0-# Hotel API

# ----- VERIFICATIONS
### Check Availability
GET http://localhost:5001/disponibilidad?huespedes=2&fecha_ingreso=2023-06-15&cantidad_noches=3

### Verify User
GET http://localhost:5001/user/username/password



# ----- BOOKINGS
### Get Bookings
GET http://localhost:5001/reservas

### Create Booking
POST http://localhost:5001/reserva
Content-Type: application/json

{
    "numero_habitacion": 101,
    "huespedes": 2,
    "fecha_ingreso": "2023-06-15",
    "cantidad_noches": 3,
    "nombre": "John Doe",
    "mail": "john.doe@example.com"
}

### Cancel Booking
DELETE http://localhost:5001/cancelar_reserva
Content-Type: application/json

{
    "id": 5,
    "numero_habitacion": 5,
    "fecha_ingreso": "2024-06-14",
    "nombre": "persona",
    "mail": "persona@example.com"
}

### Change Booking
PATCH http://localhost:5001/cambiar_reserva
Content-Type: application/json

{
    "id": 4,
    "numero_habitacion": 2,
    "nueva_fecha_ingreso": "2023-06-18",
    "nuevas_noches": 5
}



# ----- ROOMS
### Get Rooms
GET http://localhost:5001/habitaciones

### Create Room
POST http://localhost:5001/agregar_habitacion
Content-Type: application/json

{
    "numero": 206,
    "precio": 200,
    "capacidad": 2,
    "descripcion": "Habitacion doble con vista al jardin",
    "promocion": "Oferta de invierno"
}

### Delete room
DELETE http://localhost:5001/eliminar_habitacion
Content-Type: application/json

{
    "numero": 205
}


# ----- CONTACTS 
### Get Contacts
GET http://localhost:5001/contactos

### Create Contact
POST http://localhost:5001/agregar_contacto
Content-Type: application/json

{
    "nombre": "Persona",
    "mail": "persona@example.com",
    "asunto": "Consulta sobre reservas",
    "mensaje": "Tengo una duda sobre las politicas de cancelacion"
}

### Delete Contact
DELETE http://localhost:5001/eliminar_contacto
Content-Type: application/json

{
    "id": 1
}