services:
  db:
    image: mysql:latest
    container_name: database_container
    restart: always
    ports:
      - '3309:3306'
    environment:
      MYSQL_DATABASE: tp_database
      MYSQL_ROOT_PASSWORD: scrumbeasts
      MYSQL_USER: usuario
      MYSQL_PASSWORD: scrumbeasts
    volumes:
      - ../mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
